name: post-count-cron
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
        run: |
          curl -s https://github.com/dungnguyen-art/strapi-i18n/blob/main/src/api/article/controllers/article.js