name: Run fetchFromGithub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Run fetchFromGithub.js
      run: node script/fetchFromGithub.js

    - name: Set result as an output
      run: echo "::set-output name=fetchResult::$(cat ${{ steps.fetch-result.outputs.stdout }})"
    
    - name: Use the fetchResult
      run: echo "The fetchResult is ${{ steps.fetch-result.outputs.fetchResult }}"

